name: Conan Test Workflow

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name : Install Rclone
        run: apt install rclone

      - name: Install Conan
        run: pip install conan

      - name: Conan Install and Test
        run: |
          conan profile detect --force
          conan install . -of build --build=missing
          conan create .

